version: '3'
services:
  web-scraper:
    build: ./scraper
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://your_db_user:your_db_password@postgres/your_db_name
    volumes:
      - ./scraper:/app

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=your_db_name
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local